version: '3'

services:
  django:
    build: .
    image: dev_drf_logger
    ports:
      - "8000:8000"
    volumes:
      - ./:/workdir
    command: >
      bash -c "pip uninstall -y drf-logger &&
               python setup.py develop &&
               cd example_project &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
